#!/bin/bash

cmd=$1

usage() {
  echo "$0 - Usage"
  echo " - build   - build the image"
  echo " - run      - run a command in image"
  echo " - start    - start the app"
  echo " - stop     - stop the app"
}

image_name() {
  path=`pwd`
  echo `basename $path`
}

app_default_args() {
  if [ -e .dexrc ]; then
    args=$(cat .dexrc | grep default_args | awk '{$1=""; print $0}')
    echo $args
  fi
}

cmd_build() {
  image=$(image_name)
  echo "Building image for <${image}>"
  docker build -t $image .
}

cmd_start() {
  image=$(image_name)
  echo "Running <${image}>"
  docker run -d --name $image $image
}

cmd_stop() {
  image=$(image_name)
  echo "Stopping <${image}>"
  docker stop $image
  echo "Cleaning up"
  docker rm $image
}

cmd_run() {
  args=$(app_default_args)
  image=$(image_name)
  run_cmd="docker run --rm -ti ${args} ${image} $*"
  echo "Running $run_cmd"
  $run_cmd
}

case $1 in
  run)
    command=${*:2}
    cmd_run $command
    ;;
  build)
    cmd_build
    ;;
  start)
    cmd_start
    ;;
  stop)
    cmd_stop
    ;;
  *)
    usage
    ;;
esac
