#!/bin/bash

cmd=$1

usage() {
  echo "$0 - Usage"
  echo " - build   - build the image"
  echo " - run      - run a command in image"
  echo " - start    - start the app"
  echo " - stop     - stop the app"
}

image_name() {
  path=`pwd`
  echo `basename $path`
}

cmd_build() {
  image=$(image_name)
  echo "Building image for <${image}>"
  docker build -t $image .
}

cmd_start() {
  image=$(image_name)
  echo "Running <${image}>"
  docker run -d --name $image $image
}

cmd_stop() {
  image=$(image_name)
  echo "Stopping <${image}>"
  docker stop $image
  echo "Cleaning up"
  docker rm $image
}

cmd_run() {
  echo "execute a command in the docker image"
}

case $1 in
  run)
    cmd_run
    ;;
  build)
    cmd_build
    ;;
  start)
    cmd_start
    ;;
  stop)
    cmd_stop
    ;;
  *)
    usage
    ;;
esac
