#!/bin/bash -e

cmd=$1

usage() {
  echo "$0 - Usage"
  echo " - build    - build the image"
  echo " - run      - run a command in image"
  echo " - start    - start the app"
  echo " - stop     - stop the app"
  echo " - respin   - stop, build, start"
  echo " - watch    - tail and watch the logs"
}

image_name() {
  path=`pwd`
  echo -n `basename $path`
}

app_devmount_args() {
  if [ -e .dockitrc ]; then
    vol=$(cat .dockitrc | grep dev_mount | awk '{$1=""; print $0}' | sed -e 's/^ *//' -e 's/ *$//')
    if [ "$vol" != "" ]; then
      cwd=$(pwd)
      echo -n "-v ${cwd}:${vol}"
    fi
  fi
}

app_default_args() {
  if [ -e .dockitrc ]; then
    args=$(cat .dockitrc | grep default_args | awk '{$1=""; print $0}')
    echo -n $args
  fi
}

app_env_args() {
  if [ -e .dockitrc ]; then
    envs=$(cat .dockitrc | grep env | awk '{$1=""; print $0}' | sed -e 's/^ *//' -e 's/ *$//')
    for env in $envs; do
      echo -n " -e \"${env}\""
    done
  fi
}

app_socat_map_cmd() {
  if [ -e .dockitrc ]; then
    ports=$(cat .dockitrc | grep host_nat | awk '{$1=""; print $0}' | sed -e 's/^ *//' -e 's/ *$//')
    for port in $ports; do
      echo -n "socat TCP4-LISTEN:${port},fork,reuseaddr TCP4:172.17.42.1:${port} & "
    done
  fi
}

dockerfile_cmd() {
  cmd=$(cat Dockerfile | grep CMD | awk '{$1=""; print $0}')
  echo $cmd
}

cmd_build() {
  image=$(image_name)
  echo "Building image for <${image}>"
  docker build -t $image .
}

cmd_start() {
  cmd=$(dockerfile_cmd)
  args="$(app_default_args) $(app_devmount_args)"
  image=$(image_name)
  cmd="$(app_socat_map_cmd) ${cmd}"
  run_cmd="docker run -d --name $image ${args} ${image} sh -c '${cmd}'"
  eval $run_cmd
}

cmd_stop() {
  image=$(image_name)
  echo "Stopping <${image}>"
  docker stop $image
  echo "Cleaning up"
  docker rm $image
}

cmd_run() {
  cmd=$*
  args="$(app_default_args) $(app_devmount_args) $(app_env_args)"
  image=$(image_name)
  cmd="$(app_socat_map_cmd) ${cmd}"
  run_cmd="docker run --rm -ti ${args} ${image} sh -c '${cmd}'"
  echo "Running $run_cmd"
  eval $run_cmd
}

cmd_watch() {
  echo "Watching Logs"
  image=$(image_name)
  docker logs -tf $image
}

case $1 in
  run)
    command=${*:2}
    cmd_run $command
    ;;
  build)
    cmd_build
    ;;
  start)
    command=${*:2}
    cmd_start $command
    ;;
  stop)
    cmd_stop
    ;;
  watch)
    cmd_watch
    ;;
  respin)
    cmd_stop
    cmd_build
    cmd_start
    ;;
  *)
    usage
    ;;
esac
